-- 코드를 입력하세요
SELECT P.PRODUCT_ID,P.PRODUCT_NAME, (P.PRICE* SUM(F.AMOUNT)) AS TOTAL_SALES
FROM FOOD_PRODUCT P LEFT JOIN FOOD_ORDER F
ON P.PRODUCT_ID = F.PRODUCT_ID
WHERE YEAR(F.PRODUCE_DATE)='2022'
AND MONTH(F.PRODUCE_DATE)='05'
GROUP BY P.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID;