-- 코드를 입력하세요
SELECT FLAVOR
FROM (
    SELECT 
        F.FLAVOR,
        F.TOTAL_ORDER + COALESCE(SUM(J.TOTAL_ORDER), 0) AS TOTAL_ORDER_SUM
    FROM 
        FIRST_HALF F
    LEFT JOIN 
        JULY J 
    ON 
        F.FLAVOR = J.FLAVOR
    GROUP BY 
        F.FLAVOR, F.TOTAL_ORDER
) AS COMBINED_RESULTS
ORDER BY 
    TOTAL_ORDER_SUM DESC
LIMIT 3;