-- 코드를 작성해주세요
SELECT SUM(G.SCORE) AS SCORE, G.EMP_NO, E.EMP_NAME, E.POSITION,E.EMAIL
FROM HR_GRADE G LEFT JOIN HR_EMPLOYEES E
ON G.EMP_NO = E.EMP_NO
GROUP BY G.EMP_NO , G.YEAR
HAVING G.YEAR='2022'
ORDER BY SUM(G.SCORE) DESC 
LIMIT 1;